# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotoObjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(blank=True, max_length=64, verbose_name='autor')),
                ('descripcion', models.CharField(blank=True, max_length=256, verbose_name='descripcion')),
                ('archivo', models.ImageField(upload_to='img_objects')),
            ],
        ),
        migrations.CreateModel(
            name='FotoObjeto_tmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(blank=True, max_length=64, verbose_name='autor')),
                ('descripcion', models.CharField(blank=True, max_length=256, verbose_name='descripcion')),
                ('archivo', models.ImageField(upload_to='img_objects')),
            ],
        ),
        migrations.CreateModel(
            name='FotoSitio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(blank=True, max_length=64, verbose_name='autor')),
                ('descripcion', models.CharField(blank=True, max_length=256, verbose_name='descripcion')),
                ('archivo', models.ImageField(upload_to='img_sites')),
            ],
        ),
        migrations.CreateModel(
            name='FotoSitio_tmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(blank=True, max_length=64, verbose_name='autor')),
                ('descripcion', models.CharField(blank=True, max_length=256, verbose_name='descripcion')),
                ('archivo', models.ImageField(upload_to='img_sites')),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, verbose_name='Objeto_tmp')),
                ('descripcion', models.CharField(max_length=256, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Objeto_tmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, verbose_name='Objeto_tmp')),
                ('descripcion', models.CharField(max_length=256, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Site3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Site_tmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subtipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, verbose_name='subtipo')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, verbose_name='tipo')),
            ],
        ),
        migrations.AddField(
            model_name='subtipo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tipo'),
        ),
        migrations.AddField(
            model_name='objeto_tmp',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Site_tmp'),
        ),
        migrations.AddField(
            model_name='objeto_tmp',
            name='subtipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Subtipo'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Site3'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='subtipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Subtipo'),
        ),
        migrations.AddField(
            model_name='fotositio_tmp',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Site_tmp'),
        ),
        migrations.AddField(
            model_name='fotositio',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Site3'),
        ),
        migrations.AddField(
            model_name='fotoobjeto_tmp',
            name='objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Objeto_tmp'),
        ),
        migrations.AddField(
            model_name='fotoobjeto',
            name='objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Objeto'),
        ),
    ]
